# fly.toml
app = "codealpha_ecommerce_123"  # Change this (e.g., "my-django-shop")
primary_region = "iad"  # Virginia (fastest free tier)

[build]
command = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[http_service]
internal_port = 8000
force_https = true

[[services]]
internal_port = 8000
protocol = "tcp"
script_checks = []